/*
** Show the Windows system colors, which are defined by
** the current colors scheme or desktop theme.
**
** - Philippe Majerus
*/

// Turn on strict mode for this file.
"use strict";

function showSysColors()
{
	var ansi = new ActiveXObject("Majerus.ANSI");
	var text = new ActiveXObject("Majerus.Text");

	// Underline a string using ANSI/VT
	function underline(text)
	{
		return "\x1B[4m" + text + "\x1B[24m";
	}
	
	// OLE Colors for Windows color scheme
	var clr = {
		scrollBars:              0x80000000,
		desktop:                 0x80000001,
		activeTitleBar:          0x80000002,
		inactiveTitleBar:        0x80000003,
		menuBar:                 0x80000004,
		windowBackground:        0x80000005,
		windowFrame:             0x80000006,
		menuText:                0x80000007,
		windowText:              0x80000008,
		titleBarText:            0x80000009,
		activeBorder:            0x8000000A,
		inactiveBorder:          0x8000000B,
		applicationWorkspace:    0x8000000C,
		highlight:               0x8000000D,
		highlightText:           0x8000000E,
		buttonFace:              0x8000000F,
		buttonShadow:            0x80000010,
		grayText:                0x80000011,
		buttonText:              0x80000012,
		inactiveCaptionText:     0x80000013,
		threeDHighlight:         0x80000014,
		threeDDKShadow:          0x80000015,
		threeDLight:             0x80000016,
		infoText:                0x80000017,
		infoBackground:          0x80000018,
		// unused/reserved:      0x80000019,
		hotlight:                0x8000001A,
		gradientActiveCaption:   0x8000001B,
		gradientInactiveCaption: 0x8000001C,
		flatMenuHighlight:       0x8000001D,
		flatMenuBar:             0x8000001E
	};
	
	var names = ["Scroll Bars","Desktop","Active Title Bar","Inactive Title Bar","Menu Bar","Window Background","Window Frame","Menu Text","Window Text","Title Bar Text","Active Border","Inactive Border","Application Workspace","Highlight","Hightlight Text","Button Face","Button Shadow","Gray Text (disabled)","Button Text","Inactive Caption Text","3D Highlight","3D Dark Shadow","3D Light","Info Text","Info Background","","Hot-tracked","Active TB Gradient","Inactive TB Gradient","Flat Menu Highlight","Flat Menu Bar"];
	
	// This	is an ANSI-art version of the color scheme preview
	// Note system colors are retrieved and converted to their RGB values when control sequences are generated by the Majerus.ANSI
	// foreColorRGB, backColorRGB and colorsRGB methods.
	// So it happens at runtime on the system where the ANSI component is running and in its user's context preferences.
	var preview = [
		"",
		"Windows color scheme preview:",
		ansi.backColorRGB(clr.desktop) + "                                                  " + ansi.backColorRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveCaptionText,clr.inactiveTitleBar) + " Inactive Window                            " + ansi.backColorRGB(clr.desktop) + "     " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502                                          \u2502" + ansi.backColorRGB(clr.desktop) + "     " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.titleBarText, clr.activeTitleBar) +" Active Window                              " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.menuText,clr.menuBar) +"  Normal " + ansi.foreColorRGB(clr.grayText) + " Disabled " + ansi.colorsRGB(clr.highlightText,clr.highlight) + " Selected " + ansi.colorsRGB(clr.menuText,clr.menuBar) + "               " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502" + ansi.foreColorRGB(clr.windowText) + "Window Text                               " + ansi.colorsRGB(clr.titleBarText,clr.buttonFace) + "\u25B2" + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502                                          " + ansi.backcolorRGB(clr.scrollBars) + " " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502                                          " + ansi.backcolorRGB(clr.scrollBars) + " " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502  " + ansi.colorsRGB(clr.titleBarText, clr.activeTitleBar) + " Message Box                  " + ansi.backColorRGB(clr.windowBackground) + "          " + ansi.backcolorRGB(clr.scrollBars) + " " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + " Message Text                 " + ansi.backColorRGB(clr.windowBackground) + "          " + ansi.backcolorRGB(clr.scrollBars) + " " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "                              " + ansi.backColorRGB(clr.windowBackground) + "          " + ansi.backcolorRGB(clr.scrollBars) + " " + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.applicationWorkspace) + "\u2514\u2500\u2500\u2500"+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.threeDHighlight,clr.threeDLight) + "\u2588" + "\u2580\u2580\u2580\u2580\u2580\u2580\u2580" + ansi.backColorRGB(clr.buttonShadow) + "\u2580" + ansi.foreColorRGB(clr.threeDDKShadow) + "\u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.backColorRGB(clr.windowBackground) + "          " + ansi.colorsRGB(clr.titleBarText,clr.buttonFace) + "\u25BC" + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + "     "+ ansi.colorsRGB(clr.activeBorder,clr.windowBackground) +"\u2514\u2500\u2500" + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.threeDHighlight,clr.threeDLight) + "\u2588 " + ansi.colorsRGB(clr.buttonText,clr.buttonFace)+"  OK  " + ansi.colorsRGB(clr.threeDDKShadow,clr.buttonShadow) + " \u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.colorsRGB(clr.activeBorder,clr.windowBackground) + "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518" + ansi.backColorRGB(clr.desktop) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + "        " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.threeDDKShadow,clr.threeDHighlight) + "\u2584" + ansi.backColorRGB(clr.buttonShadow) + "\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.backColorRGB(clr.desktop) + "            " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + "        " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "                              " + ansi.backColorRGB(clr.desktop) + "            " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.desktop) + "                                                  " + ansi.backColorRGB(),
		"",
		"Gradient title bars: (Win98 look)",
		" " + ansi.colorsRGB(clr.inactiveCaptionText, clr.inactiveTitleBar) + " Inactive Window    " + ansi.foreColorRGB(clr.gradientInactiveCaption) + "\u2591\u2591\u2591\u2591\u2591\u2591\u2592\u2592\u2592\u2592\u2592\u2592\u2593\u2593\u2593\u2593\u2593\u2593\u2588\u2588\u2588\u2588\u2588\u2588" + ansi.colorsRGB(),
		"     " + ansi.colorsRGB(clr.titleBarText, clr.activeTitleBar) + " Active Window      " + ansi.foreColorRGB(clr.gradientActiveCaption) + "\u2591\u2591\u2591\u2591\u2591\u2591\u2592\u2592\u2592\u2592\u2592\u2592\u2593\u2593\u2593\u2593\u2593\u2593\u2588\u2588\u2588\u2588\u2588\u2588" + ansi.colorsRGB(),
		"",
		"Flat menu style:",
		"     " + ansi.colorsRGB(clr.menuText,clr.flatMenuBar) + "  Normal " + ansi.foreColorRGB(clr.grayText) + " Disabled " + ansi.foreColorRGB(clr.flatMenuHighlight) + " Selected " + "               " + ansi.colorsRGB(),
		"",
		"Hot-tracking / hyperlinks:",
		"      " + ansi.foreColorRGB(clr.hotlight) + "Link text" + ansi.foreColorRGB(),
		"",
		"Infotips:",
		"   " + ansi.colorsRGB(clr.infoText,clr.infoBackground) + " Tooltip text "+ ansi.backColorRGB()
	];
	
	echo();
	echo(underline("Windows system colors".toUpperCase()));
	echo("These colors depend on the user's current colors scheme.");
	echo();
	for (var i = 0; i<0x1F; i++)
	{
			echo((i<0x10?"0":"") + (i.toString(16).toUpperCase()) + " " + ansi.foreColorRGB(0x80000000+i) + "\u2588\u2588" + ansi.foreColorRGB() + " " + names[i] + text.padding(23-names[i].length,' ') + preview[i]);
	}
	echo();
}
