/*
** Show the Windows system colors, which are defined by
** the current colors scheme or desktop theme.
**
** - Philippe Majerus
*/

// Turn on strict mode for this file.
"use strict";

function showSysColors()
{
	var ansi = new ActiveXObject("Majerus.ANSI");
	var text = new ActiveXObject("Majerus.Text");

	// Underline a string using ANSI/VT
	function underline(text)
	{
		return "\x1B[4m" + text + "\x1B[24m";
	}
	
	// OLE Colors for Windows color scheme
	var clr = {
		scrollbar:                0x80000000,
		background:               0x80000001,
		activeTitle:              0x80000002,
		inactiveTitle:            0x80000003,
		menu:                     0x80000004,
		window:                   0x80000005,
		windowFrame:              0x80000006,
		menuText:                 0x80000007,
		windowText:               0x80000008,
		titleText:                0x80000009,
		activeBorder:             0x8000000A,
		inactiveBorder:           0x8000000B,
		appWorkspace:             0x8000000C,
		hilight:                  0x8000000D,
		hilightText:              0x8000000E,
		buttonFace:               0x8000000F,
		buttonShadow:             0x80000010,
		grayText:                 0x80000011,
		buttonText:               0x80000012,
		inactiveTitleText:        0x80000013,
		buttonHilight:            0x80000014,
		buttonDkShadow:           0x80000015,
		buttonLight:              0x80000016,
		infoText:                 0x80000017,
		infoWindow:               0x80000018,
		buttonAlternateFace:      0x80000019,
		hotTrackingColor:         0x8000001A,
		gradientActiveTitle:      0x8000001B,
		gradientInactiveTitle:    0x8000001C,
		menuHilight:              0x8000001D,
		menuBar:                  0x8000001E
	};
	
	var names = ["Scroll Bars","Desktop Background","Active Title Bar","Inactive Title Bar","Menu Bar","Window Background","Window Frame","Menu Text","Window Text","Active Title Text","Active Border","Inactive Border","Application Workspace","Highlight","Highlight Text","Button Face","Button Shadow","Gray (disabled) Text","Button Text","Inactive Title Text","3D Highlight","3D Dark Shadow","3D Light","Info Text","Info Background","Alternate Button Face","Hot-tracked","Active TB Gradient","Inactive TB Gradient","Flat Menu Highlight","Flat Menu Bar"];
	
	// This	is an ANSI-art version of the color scheme preview
	// Note system colors are retrieved and converted to their RGB values when control sequences are generated by the Majerus.ANSI
	// foreColorRGB, backColorRGB and colorsRGB methods.
	// So it happens at runtime on the system where the ANSI component is running and in its user's context preferences.
	var preview = [
		"",
		"Windows color scheme preview:",
		ansi.backColorRGB(clr.background) + "                                                  " + ansi.backColorRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveTitleText,clr.inactiveTitle) + " Inactive Window                            " + ansi.backColorRGB(clr.background) + "     " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502                                          \u2502" + ansi.backColorRGB(clr.background) + "     " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.titleText, clr.activeTitle) +" Active Window                              " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.menuText,clr.menu) +"  Normal " + ansi.foreColorRGB(clr.grayText) + " Disabled " + ansi.colorsRGB(clr.hilightText,clr.hilight) + " Selected " + ansi.colorsRGB(clr.menuText,clr.menu) + "               " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502" + ansi.foreColorRGB(clr.windowText) + "Window Text                               " + ansi.colorsRGB(clr.titleBarText,clr.buttonFace) + "\u25B2" + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502                                          " + ansi.backcolorRGB(clr.scrollbar) + " " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502                                          " + ansi.backcolorRGB(clr.scrollbar) + " " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502  " + ansi.colorsRGB(clr.titleText, clr.activeTitle) + " Message Box                  " + ansi.backColorRGB(clr.window) + "          " + ansi.backcolorRGB(clr.scrollbar) + " " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + " Message Text                 " + ansi.backColorRGB(clr.window) + "          " + ansi.backcolorRGB(clr.scrollbar) + " " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2502   "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "                              " + ansi.backColorRGB(clr.window) + "          " + ansi.backcolorRGB(clr.scrollbar) + " " + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(clr.inactiveBorder,clr.appWorkspace) + "\u2514\u2500\u2500\u2500"+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2502  " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.buttonHilight,clr.buttonLight) + "\u2588" + "\u2580\u2580\u2580\u2580\u2580\u2580\u2580" + ansi.backColorRGB(clr.buttonShadow) + "\u2580" + ansi.foreColorRGB(clr.buttonDkShadow) + "\u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.backColorRGB(clr.window) + "          " + ansi.colorsRGB(clr.titleBarText,clr.buttonFace) + "\u25BC" + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + "     "+ ansi.colorsRGB(clr.activeBorder,clr.window) +"\u2514\u2500\u2500" + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.buttonHilight,clr.buttonLight) + "\u2588 " + ansi.colorsRGB(clr.buttonText,clr.buttonFace)+"  OK  " + ansi.colorsRGB(clr.buttonDkShadow,clr.buttonShadow) + " \u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.colorsRGB(clr.activeBorder,clr.window) + "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518" + ansi.backColorRGB(clr.background) + " " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + "        " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "          " + ansi.colorsRGB(clr.buttonDkShadow,clr.buttonHilight) + "\u2584" + ansi.backColorRGB(clr.buttonShadow) + "\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2588" + ansi.backColorRGB(clr.buttonFace) + "          " + ansi.backColorRGB(clr.background) + "            " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + "        " + ansi.colorsRGB(clr.buttonText, clr.buttonFace) + "                              " + ansi.backColorRGB(clr.background) + "            " + ansi.colorsRGB(),
		ansi.backColorRGB(clr.background) + "                                                  " + ansi.backColorRGB(),
		"",
		"Gradient title bars: (Win98 look)",
		" " + ansi.colorsRGB(clr.inactiveTitleText, clr.inactiveTitle) + " Inactive Window    " + ansi.foreColorRGB(clr.gradientInactiveTitle) + "\u2591\u2591\u2591\u2591\u2591\u2591\u2592\u2592\u2592\u2592\u2592\u2592\u2593\u2593\u2593\u2593\u2593\u2593\u2588\u2588\u2588\u2588\u2588\u2588" + ansi.colorsRGB(),
		"     " + ansi.colorsRGB(clr.titleText, clr.activeTitle) + " Active Window      " + ansi.foreColorRGB(clr.gradientActiveTitle) + "\u2591\u2591\u2591\u2591\u2591\u2591\u2592\u2592\u2592\u2592\u2592\u2592\u2593\u2593\u2593\u2593\u2593\u2593\u2588\u2588\u2588\u2588\u2588\u2588" + ansi.colorsRGB(),
		"",
		"Flat menu style:",
		"     " + ansi.colorsRGB(clr.menuText,clr.menuBar) + "  Normal " + ansi.foreColorRGB(clr.grayText) + " Disabled " + ansi.foreColorRGB(clr.menuHilight) + " Selected " + "               " + ansi.colorsRGB(),
		"",
		"Hot-tracking / hyperlinks:",
		"      " + ansi.foreColorRGB(clr.hotTrackingColor) + "Link text" + ansi.foreColorRGB(),
		"",
		"Infotips:",
		"   " + ansi.colorsRGB(clr.infoText,clr.infoWindow) + " Tooltip text "+ ansi.backColorRGB()
	];
	
	echo();
	echo(underline("Windows system colors".toUpperCase()));
	echo("These colors depend on the user's current colors scheme.");
	echo();
	for (var i = 0; i<0x1F; i++)
	{
			echo((i<0x10?"0":"") + (i.toString(16).toUpperCase()) + " " + ansi.foreColorRGB(0x80000000+i) + "\u2588\u2588" + ansi.foreColorRGB() + " " + names[i] + text.padding(23-names[i].length,' ') + preview[i]);
	}
	echo();
}
